Industry.find_or_create_by(name: "Art & Design")
Industry.find_or_create_by(name: "Consulting")
Industry.find_or_create_by(name: "Education")
Industry.find_or_create_by(name: "Energy")
Industry.find_or_create_by(name: "Engineering")
Industry.find_or_create_by(name: "Finance")
Industry.find_or_create_by(name: "Food")
Industry.find_or_create_by(name: "Government")
Industry.find_or_create_by(name: "Healthcare")
Industry.find_or_create_by(name: "Legal")
Industry.find_or_create_by(name: "Media and Advertising")
Industry.find_or_create_by(name: "Retail")
Industry.find_or_create_by(name: "Technology")
Industry.find_or_create_by(name: "Other")


Topic.find_or_create_by(name: 'General Networking')
Topic.find_or_create_by(name: 'Sharing Expertise')
Topic.find_or_create_by(name: 'Mentorship')
Topic.find_or_create_by(name: 'Looking to Hire')
Topic.find_or_create_by(name: 'Job Opportunities')
Topic.find_or_create_by(name: 'Investing')
Topic.find_or_create_by(name: 'Seeking Investment')

Location.find_or_create_by(area: 'Greater Denver Area, US')
Location.find_or_create_by(area: 'Greater New York City Area, US')
Location.find_or_create_by(area: 'Greater Atlanta Area, US')
Location.find_or_create_by(area: 'San Francisco Bay Area, US')
Location.find_or_create_by(area: 'Washington D.C. Metro Area, US')
Location.find_or_create_by(area: 'Greater Chicago Area, US')
Location.find_or_create_by(area: 'Greater Boston Area, US')

Meeting.find_or_create_by(name: 'Coffee')
Meeting.find_or_create_by(name: 'Lunch')
Meeting.find_or_create_by(name: 'A drink')
Meeting.find_or_create_by(name: 'Phone call')
Meeting.find_or_create_by(name: 'Video chat')

Function.find_or_create_by(name: 'Strategy')
Function.find_or_create_by(name: 'Operations')
Function.find_or_create_by(name: 'Finance & Accounting')
Function.find_or_create_by(name: 'Sales')
Function.find_or_create_by(name: 'Marketing')
Function.find_or_create_by(name: 'Product & Engineering')
Function.find_or_create_by(name: 'Talent & Organization')
