Industry.find_or_create_by(name: "Art & Design")
Industry.find_or_create_by(name: "Education")
Industry.find_or_create_by(name: "Energy")
Industry.find_or_create_by(name: "Engineering")
Industry.find_or_create_by(name: "Finance")
Industry.find_or_create_by(name: "Food")
Industry.find_or_create_by(name: "Government")
Industry.find_or_create_by(name: "Healthcare")
Industry.find_or_create_by(name: "Legal")
Industry.find_or_create_by(name: "Media and Advertising")
Industry.find_or_create_by(name: "Retail")
Industry.find_or_create_by(name: "Technology")
Industry.find_or_create_by(name: "Other")


Topic.find_or_create_by(name: 'General Networking')
Topic.find_or_create_by(name: 'Sharing Expertise')
Topic.find_or_create_by(name: 'Mentorship')
Topic.find_or_create_by(name: 'Looking to Hire')
Topic.find_or_create_by(name: 'Job Opportunities')
Topic.find_or_create_by(name: 'Investing')
Topic.find_or_create_by(name: 'Seeking Investment')
