
Industry.find_or_create_by(name: "Education")
Industry.find_or_create_by(name: "Fashion")
Industry.find_or_create_by(name: "Finance")
Industry.find_or_create_by(name: "Food")
Industry.find_or_create_by(name: "Government")
Industry.find_or_create_by(name: "Healthcare")
Industry.find_or_create_by(name: "Legal")
Industry.find_or_create_by(name: "Media and Advertising")
Industry.find_or_create_by(name: "Retail")
Industry.find_or_create_by(name: "Technology")
Industry.find_or_create_by(name: "Other")